package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AreaTrabajo generated by hbm2java
 */
public class AreaTrabajo  implements java.io.Serializable {


     private Integer idArea;
     private String nombreArea;
     private Boolean estadoArea;
     private Set habitacioneses = new HashSet(0);
     private Set enfermeras = new HashSet(0);
     private Set cajeros = new HashSet(0);
     private Set empleadoLaboratorios = new HashSet(0);
     private Set medicos = new HashSet(0);

    public AreaTrabajo() {
    }

	
    public AreaTrabajo(String nombreArea) {
        this.nombreArea = nombreArea;
    }
    public AreaTrabajo(String nombreArea, Boolean estadoArea, Set habitacioneses, Set enfermeras, Set cajeros, Set empleadoLaboratorios, Set medicos) {
       this.nombreArea = nombreArea;
       this.estadoArea = estadoArea;
       this.habitacioneses = habitacioneses;
       this.enfermeras = enfermeras;
       this.cajeros = cajeros;
       this.empleadoLaboratorios = empleadoLaboratorios;
       this.medicos = medicos;
    }
   
    public Integer getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(Integer idArea) {
        this.idArea = idArea;
    }
    public String getNombreArea() {
        return this.nombreArea;
    }
    
    public void setNombreArea(String nombreArea) {
        this.nombreArea = nombreArea;
    }
    public Boolean getEstadoArea() {
        return this.estadoArea;
    }
    
    public void setEstadoArea(Boolean estadoArea) {
        this.estadoArea = estadoArea;
    }
    public Set getHabitacioneses() {
        return this.habitacioneses;
    }
    
    public void setHabitacioneses(Set habitacioneses) {
        this.habitacioneses = habitacioneses;
    }
    public Set getEnfermeras() {
        return this.enfermeras;
    }
    
    public void setEnfermeras(Set enfermeras) {
        this.enfermeras = enfermeras;
    }
    public Set getCajeros() {
        return this.cajeros;
    }
    
    public void setCajeros(Set cajeros) {
        this.cajeros = cajeros;
    }
    public Set getEmpleadoLaboratorios() {
        return this.empleadoLaboratorios;
    }
    
    public void setEmpleadoLaboratorios(Set empleadoLaboratorios) {
        this.empleadoLaboratorios = empleadoLaboratorios;
    }
    public Set getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Set medicos) {
        this.medicos = medicos;
    }




}


