package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cajero generated by hbm2java
 */
public class Cajero  implements java.io.Serializable {


     private Integer idCajero;
     private AreaTrabajo areaTrabajo;
     private Cargo cargo;
     private Usuario usuario;
     private String cedulaCajero;
     private String sexoCajero;
     private BigDecimal salario;
     private Date fechaContratacion;
     private String direccion;
     private boolean estado;
     private byte[] foto;
     private Set prestamos = new HashSet(0);
     private Set hrsExtrases = new HashSet(0);
     private Set facturaConsultas = new HashSet(0);
     private Set nominas = new HashSet(0);

    public Cajero() {
    }

	
    public Cajero(AreaTrabajo areaTrabajo, Cargo cargo, Usuario usuario, String cedulaCajero, String sexoCajero, BigDecimal salario, Date fechaContratacion, String direccion, boolean estado) {
        this.areaTrabajo = areaTrabajo;
        this.cargo = cargo;
        this.usuario = usuario;
        this.cedulaCajero = cedulaCajero;
        this.sexoCajero = sexoCajero;
        this.salario = salario;
        this.fechaContratacion = fechaContratacion;
        this.direccion = direccion;
        this.estado = estado;
    }
    public Cajero(AreaTrabajo areaTrabajo, Cargo cargo, Usuario usuario, String cedulaCajero, String sexoCajero, BigDecimal salario, Date fechaContratacion, String direccion, boolean estado, byte[] foto, Set prestamos, Set hrsExtrases, Set facturaConsultas, Set nominas) {
       this.areaTrabajo = areaTrabajo;
       this.cargo = cargo;
       this.usuario = usuario;
       this.cedulaCajero = cedulaCajero;
       this.sexoCajero = sexoCajero;
       this.salario = salario;
       this.fechaContratacion = fechaContratacion;
       this.direccion = direccion;
       this.estado = estado;
       this.foto = foto;
       this.prestamos = prestamos;
       this.hrsExtrases = hrsExtrases;
       this.facturaConsultas = facturaConsultas;
       this.nominas = nominas;
    }
   
    public Integer getIdCajero() {
        return this.idCajero;
    }
    
    public void setIdCajero(Integer idCajero) {
        this.idCajero = idCajero;
    }
    public AreaTrabajo getAreaTrabajo() {
        return this.areaTrabajo;
    }
    
    public void setAreaTrabajo(AreaTrabajo areaTrabajo) {
        this.areaTrabajo = areaTrabajo;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCedulaCajero() {
        return this.cedulaCajero;
    }
    
    public void setCedulaCajero(String cedulaCajero) {
        this.cedulaCajero = cedulaCajero;
    }
    public String getSexoCajero() {
        return this.sexoCajero;
    }
    
    public void setSexoCajero(String sexoCajero) {
        this.sexoCajero = sexoCajero;
    }
    public BigDecimal getSalario() {
        return this.salario;
    }
    
    public void setSalario(BigDecimal salario) {
        this.salario = salario;
    }
    public Date getFechaContratacion() {
        return this.fechaContratacion;
    }
    
    public void setFechaContratacion(Date fechaContratacion) {
        this.fechaContratacion = fechaContratacion;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public Set getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set prestamos) {
        this.prestamos = prestamos;
    }
    public Set getHrsExtrases() {
        return this.hrsExtrases;
    }
    
    public void setHrsExtrases(Set hrsExtrases) {
        this.hrsExtrases = hrsExtrases;
    }
    public Set getFacturaConsultas() {
        return this.facturaConsultas;
    }
    
    public void setFacturaConsultas(Set facturaConsultas) {
        this.facturaConsultas = facturaConsultas;
    }
    public Set getNominas() {
        return this.nominas;
    }
    
    public void setNominas(Set nominas) {
        this.nominas = nominas;
    }




}


