package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     private Integer idCargo;
     private Date fechaCreacion;
     private String nombreCargo;
     private BigDecimal salarioMin;
     private Set medicos = new HashSet(0);
     private Set cajeros = new HashSet(0);
     private Set enfermeras = new HashSet(0);
     private Set empleadoLaboratorios = new HashSet(0);

    public Cargo() {
    }

	
    public Cargo(Date fechaCreacion, String nombreCargo, BigDecimal salarioMin) {
        this.fechaCreacion = fechaCreacion;
        this.nombreCargo = nombreCargo;
        this.salarioMin = salarioMin;
    }
    public Cargo(Date fechaCreacion, String nombreCargo, BigDecimal salarioMin, Set medicos, Set cajeros, Set enfermeras, Set empleadoLaboratorios) {
       this.fechaCreacion = fechaCreacion;
       this.nombreCargo = nombreCargo;
       this.salarioMin = salarioMin;
       this.medicos = medicos;
       this.cajeros = cajeros;
       this.enfermeras = enfermeras;
       this.empleadoLaboratorios = empleadoLaboratorios;
    }
   
    public Integer getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(Integer idCargo) {
        this.idCargo = idCargo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getNombreCargo() {
        return this.nombreCargo;
    }
    
    public void setNombreCargo(String nombreCargo) {
        this.nombreCargo = nombreCargo;
    }
    public BigDecimal getSalarioMin() {
        return this.salarioMin;
    }
    
    public void setSalarioMin(BigDecimal salarioMin) {
        this.salarioMin = salarioMin;
    }
    public Set getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Set medicos) {
        this.medicos = medicos;
    }
    public Set getCajeros() {
        return this.cajeros;
    }
    
    public void setCajeros(Set cajeros) {
        this.cajeros = cajeros;
    }
    public Set getEnfermeras() {
        return this.enfermeras;
    }
    
    public void setEnfermeras(Set enfermeras) {
        this.enfermeras = enfermeras;
    }
    public Set getEmpleadoLaboratorios() {
        return this.empleadoLaboratorios;
    }
    
    public void setEmpleadoLaboratorios(Set empleadoLaboratorios) {
        this.empleadoLaboratorios = empleadoLaboratorios;
    }




}


