package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer idCompra;
     private EmpleadoLaboratorio empleadoLaboratorio;
     private Proveedor proveedor;
     private TipoCambio tipoCambio;
     private Date fechaCompra;
     private String tipoMoneda;
     private String modoCompra;
     private Set detalleCompras = new HashSet(0);

    public Compra() {
    }

	
    public Compra(EmpleadoLaboratorio empleadoLaboratorio, Proveedor proveedor, TipoCambio tipoCambio, Date fechaCompra, String tipoMoneda, String modoCompra) {
        this.empleadoLaboratorio = empleadoLaboratorio;
        this.proveedor = proveedor;
        this.tipoCambio = tipoCambio;
        this.fechaCompra = fechaCompra;
        this.tipoMoneda = tipoMoneda;
        this.modoCompra = modoCompra;
    }
    public Compra(EmpleadoLaboratorio empleadoLaboratorio, Proveedor proveedor, TipoCambio tipoCambio, Date fechaCompra, String tipoMoneda, String modoCompra, Set detalleCompras) {
       this.empleadoLaboratorio = empleadoLaboratorio;
       this.proveedor = proveedor;
       this.tipoCambio = tipoCambio;
       this.fechaCompra = fechaCompra;
       this.tipoMoneda = tipoMoneda;
       this.modoCompra = modoCompra;
       this.detalleCompras = detalleCompras;
    }
   
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
    public EmpleadoLaboratorio getEmpleadoLaboratorio() {
        return this.empleadoLaboratorio;
    }
    
    public void setEmpleadoLaboratorio(EmpleadoLaboratorio empleadoLaboratorio) {
        this.empleadoLaboratorio = empleadoLaboratorio;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public TipoCambio getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(TipoCambio tipoCambio) {
        this.tipoCambio = tipoCambio;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public String getTipoMoneda() {
        return this.tipoMoneda;
    }
    
    public void setTipoMoneda(String tipoMoneda) {
        this.tipoMoneda = tipoMoneda;
    }
    public String getModoCompra() {
        return this.modoCompra;
    }
    
    public void setModoCompra(String modoCompra) {
        this.modoCompra = modoCompra;
    }
    public Set getDetalleCompras() {
        return this.detalleCompras;
    }
    
    public void setDetalleCompras(Set detalleCompras) {
        this.detalleCompras = detalleCompras;
    }




}


