package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private Integer idDepartamento;
     private Pais pais;
     private String nombreDepartamento;
     private Set municipios = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(Pais pais, String nombreDepartamento) {
        this.pais = pais;
        this.nombreDepartamento = nombreDepartamento;
    }
    public Departamento(Pais pais, String nombreDepartamento, Set municipios) {
       this.pais = pais;
       this.nombreDepartamento = nombreDepartamento;
       this.municipios = municipios;
    }
   
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public Set getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Set municipios) {
        this.municipios = municipios;
    }




}


