package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleVenta generated by hbm2java
 */
public class DetalleVenta  implements java.io.Serializable {


     private Integer idDetalleVenta;
     private Producto producto;
     private Venta venta;
     private int unidadesVendidas;
     private BigDecimal precioVenta;

    public DetalleVenta() {
    }

    public DetalleVenta(Producto producto, Venta venta, int unidadesVendidas, BigDecimal precioVenta) {
       this.producto = producto;
       this.venta = venta;
       this.unidadesVendidas = unidadesVendidas;
       this.precioVenta = precioVenta;
    }
   
    public Integer getIdDetalleVenta() {
        return this.idDetalleVenta;
    }
    
    public void setIdDetalleVenta(Integer idDetalleVenta) {
        this.idDetalleVenta = idDetalleVenta;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public int getUnidadesVendidas() {
        return this.unidadesVendidas;
    }
    
    public void setUnidadesVendidas(int unidadesVendidas) {
        this.unidadesVendidas = unidadesVendidas;
    }
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }




}


