package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1



/**
 * DiasMedico generated by hbm2java
 */
public class DiasMedico  implements java.io.Serializable {


     private Integer idDiaMedico;
     private Medico medico;
     private boolean lunes;
     private String horaEntradaLunes;
     private String horaSalidaLunes;
     private boolean martes;
     private String horaEntradaMartes;
     private String horaSalidaMartes;
     private boolean miercoles;
     private String horaEntradaMiercoles;
     private String horaSalidaMiercoles;
     private boolean jueves;
     private String horaEntradaJueves;
     private String horaSalidaJueves;
     private boolean viernes;
     private String horaEntradaViernes;
     private String horaSalidaViernes;
     private boolean sabado;
     private String horaEntradaSabado;
     private String horaSalidaSabado;
     private boolean domingo;
     private String horaEntradaDomingo;
     private String horaSalidaDomingo;

    public DiasMedico() {
    }

    public DiasMedico(Medico medico, boolean lunes, String horaEntradaLunes, String horaSalidaLunes, boolean martes, String horaEntradaMartes, String horaSalidaMartes, boolean miercoles, String horaEntradaMiercoles, String horaSalidaMiercoles, boolean jueves, String horaEntradaJueves, String horaSalidaJueves, boolean viernes, String horaEntradaViernes, String horaSalidaViernes, boolean sabado, String horaEntradaSabado, String horaSalidaSabado, boolean domingo, String horaEntradaDomingo, String horaSalidaDomingo) {
       this.medico = medico;
       this.lunes = lunes;
       this.horaEntradaLunes = horaEntradaLunes;
       this.horaSalidaLunes = horaSalidaLunes;
       this.martes = martes;
       this.horaEntradaMartes = horaEntradaMartes;
       this.horaSalidaMartes = horaSalidaMartes;
       this.miercoles = miercoles;
       this.horaEntradaMiercoles = horaEntradaMiercoles;
       this.horaSalidaMiercoles = horaSalidaMiercoles;
       this.jueves = jueves;
       this.horaEntradaJueves = horaEntradaJueves;
       this.horaSalidaJueves = horaSalidaJueves;
       this.viernes = viernes;
       this.horaEntradaViernes = horaEntradaViernes;
       this.horaSalidaViernes = horaSalidaViernes;
       this.sabado = sabado;
       this.horaEntradaSabado = horaEntradaSabado;
       this.horaSalidaSabado = horaSalidaSabado;
       this.domingo = domingo;
       this.horaEntradaDomingo = horaEntradaDomingo;
       this.horaSalidaDomingo = horaSalidaDomingo;
    }
   
    public Integer getIdDiaMedico() {
        return this.idDiaMedico;
    }
    
    public void setIdDiaMedico(Integer idDiaMedico) {
        this.idDiaMedico = idDiaMedico;
    }
    public Medico getMedico() {
        return this.medico;
    }
    
    public void setMedico(Medico medico) {
        this.medico = medico;
    }
    public boolean isLunes() {
        return this.lunes;
    }
    
    public void setLunes(boolean lunes) {
        this.lunes = lunes;
    }
    public String getHoraEntradaLunes() {
        return this.horaEntradaLunes;
    }
    
    public void setHoraEntradaLunes(String horaEntradaLunes) {
        this.horaEntradaLunes = horaEntradaLunes;
    }
    public String getHoraSalidaLunes() {
        return this.horaSalidaLunes;
    }
    
    public void setHoraSalidaLunes(String horaSalidaLunes) {
        this.horaSalidaLunes = horaSalidaLunes;
    }
    public boolean isMartes() {
        return this.martes;
    }
    
    public void setMartes(boolean martes) {
        this.martes = martes;
    }
    public String getHoraEntradaMartes() {
        return this.horaEntradaMartes;
    }
    
    public void setHoraEntradaMartes(String horaEntradaMartes) {
        this.horaEntradaMartes = horaEntradaMartes;
    }
    public String getHoraSalidaMartes() {
        return this.horaSalidaMartes;
    }
    
    public void setHoraSalidaMartes(String horaSalidaMartes) {
        this.horaSalidaMartes = horaSalidaMartes;
    }
    public boolean isMiercoles() {
        return this.miercoles;
    }
    
    public void setMiercoles(boolean miercoles) {
        this.miercoles = miercoles;
    }
    public String getHoraEntradaMiercoles() {
        return this.horaEntradaMiercoles;
    }
    
    public void setHoraEntradaMiercoles(String horaEntradaMiercoles) {
        this.horaEntradaMiercoles = horaEntradaMiercoles;
    }
    public String getHoraSalidaMiercoles() {
        return this.horaSalidaMiercoles;
    }
    
    public void setHoraSalidaMiercoles(String horaSalidaMiercoles) {
        this.horaSalidaMiercoles = horaSalidaMiercoles;
    }
    public boolean isJueves() {
        return this.jueves;
    }
    
    public void setJueves(boolean jueves) {
        this.jueves = jueves;
    }
    public String getHoraEntradaJueves() {
        return this.horaEntradaJueves;
    }
    
    public void setHoraEntradaJueves(String horaEntradaJueves) {
        this.horaEntradaJueves = horaEntradaJueves;
    }
    public String getHoraSalidaJueves() {
        return this.horaSalidaJueves;
    }
    
    public void setHoraSalidaJueves(String horaSalidaJueves) {
        this.horaSalidaJueves = horaSalidaJueves;
    }
    public boolean isViernes() {
        return this.viernes;
    }
    
    public void setViernes(boolean viernes) {
        this.viernes = viernes;
    }
    public String getHoraEntradaViernes() {
        return this.horaEntradaViernes;
    }
    
    public void setHoraEntradaViernes(String horaEntradaViernes) {
        this.horaEntradaViernes = horaEntradaViernes;
    }
    public String getHoraSalidaViernes() {
        return this.horaSalidaViernes;
    }
    
    public void setHoraSalidaViernes(String horaSalidaViernes) {
        this.horaSalidaViernes = horaSalidaViernes;
    }
    public boolean isSabado() {
        return this.sabado;
    }
    
    public void setSabado(boolean sabado) {
        this.sabado = sabado;
    }
    public String getHoraEntradaSabado() {
        return this.horaEntradaSabado;
    }
    
    public void setHoraEntradaSabado(String horaEntradaSabado) {
        this.horaEntradaSabado = horaEntradaSabado;
    }
    public String getHoraSalidaSabado() {
        return this.horaSalidaSabado;
    }
    
    public void setHoraSalidaSabado(String horaSalidaSabado) {
        this.horaSalidaSabado = horaSalidaSabado;
    }
    public boolean isDomingo() {
        return this.domingo;
    }
    
    public void setDomingo(boolean domingo) {
        this.domingo = domingo;
    }
    public String getHoraEntradaDomingo() {
        return this.horaEntradaDomingo;
    }
    
    public void setHoraEntradaDomingo(String horaEntradaDomingo) {
        this.horaEntradaDomingo = horaEntradaDomingo;
    }
    public String getHoraSalidaDomingo() {
        return this.horaSalidaDomingo;
    }
    
    public void setHoraSalidaDomingo(String horaSalidaDomingo) {
        this.horaSalidaDomingo = horaSalidaDomingo;
    }




}


