package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EmpleadoLaboratorio generated by hbm2java
 */
public class EmpleadoLaboratorio  implements java.io.Serializable {


     private Integer idEmpleado;
     private AreaTrabajo areaTrabajo;
     private Cargo cargo;
     private Laboratorio laboratorio;
     private Usuario usuario;
     private String primerNombreEmpleado;
     private String segundoNombreEmpleado;
     private String primerApellidoEmpleado;
     private String segundoApellidoEmpleado;
     private Date fechaContratacion;
     private boolean estado;
     private String telefonoEmpleado;
     private String cedulaEmpleado;
     private String correoEmpleado;
     private String direccionEmpleado;
     private byte[] fotografiaEmpleado;
     private String sexoEmpleado;
     private Set compras = new HashSet(0);
     private Set prestamos = new HashSet(0);
     private Set inventarioGenerals = new HashSet(0);
     private Set devolucionCompras = new HashSet(0);
     private Set hrsExtrases = new HashSet(0);
     private Set nominas = new HashSet(0);
     private Set ventas = new HashSet(0);

    public EmpleadoLaboratorio() {
    }

	
    public EmpleadoLaboratorio(AreaTrabajo areaTrabajo, Cargo cargo, Laboratorio laboratorio, Usuario usuario, String primerNombreEmpleado, String segundoNombreEmpleado, String primerApellidoEmpleado, String segundoApellidoEmpleado, Date fechaContratacion, boolean estado, String telefonoEmpleado, String cedulaEmpleado, String correoEmpleado, String direccionEmpleado, String sexoEmpleado) {
        this.areaTrabajo = areaTrabajo;
        this.cargo = cargo;
        this.laboratorio = laboratorio;
        this.usuario = usuario;
        this.primerNombreEmpleado = primerNombreEmpleado;
        this.segundoNombreEmpleado = segundoNombreEmpleado;
        this.primerApellidoEmpleado = primerApellidoEmpleado;
        this.segundoApellidoEmpleado = segundoApellidoEmpleado;
        this.fechaContratacion = fechaContratacion;
        this.estado = estado;
        this.telefonoEmpleado = telefonoEmpleado;
        this.cedulaEmpleado = cedulaEmpleado;
        this.correoEmpleado = correoEmpleado;
        this.direccionEmpleado = direccionEmpleado;
        this.sexoEmpleado = sexoEmpleado;
    }
    public EmpleadoLaboratorio(AreaTrabajo areaTrabajo, Cargo cargo, Laboratorio laboratorio, Usuario usuario, String primerNombreEmpleado, String segundoNombreEmpleado, String primerApellidoEmpleado, String segundoApellidoEmpleado, Date fechaContratacion, boolean estado, String telefonoEmpleado, String cedulaEmpleado, String correoEmpleado, String direccionEmpleado, byte[] fotografiaEmpleado, String sexoEmpleado, Set compras, Set prestamos, Set inventarioGenerals, Set devolucionCompras, Set hrsExtrases, Set nominas, Set ventas) {
       this.areaTrabajo = areaTrabajo;
       this.cargo = cargo;
       this.laboratorio = laboratorio;
       this.usuario = usuario;
       this.primerNombreEmpleado = primerNombreEmpleado;
       this.segundoNombreEmpleado = segundoNombreEmpleado;
       this.primerApellidoEmpleado = primerApellidoEmpleado;
       this.segundoApellidoEmpleado = segundoApellidoEmpleado;
       this.fechaContratacion = fechaContratacion;
       this.estado = estado;
       this.telefonoEmpleado = telefonoEmpleado;
       this.cedulaEmpleado = cedulaEmpleado;
       this.correoEmpleado = correoEmpleado;
       this.direccionEmpleado = direccionEmpleado;
       this.fotografiaEmpleado = fotografiaEmpleado;
       this.sexoEmpleado = sexoEmpleado;
       this.compras = compras;
       this.prestamos = prestamos;
       this.inventarioGenerals = inventarioGenerals;
       this.devolucionCompras = devolucionCompras;
       this.hrsExtrases = hrsExtrases;
       this.nominas = nominas;
       this.ventas = ventas;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public AreaTrabajo getAreaTrabajo() {
        return this.areaTrabajo;
    }
    
    public void setAreaTrabajo(AreaTrabajo areaTrabajo) {
        this.areaTrabajo = areaTrabajo;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public Laboratorio getLaboratorio() {
        return this.laboratorio;
    }
    
    public void setLaboratorio(Laboratorio laboratorio) {
        this.laboratorio = laboratorio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getPrimerNombreEmpleado() {
        return this.primerNombreEmpleado;
    }
    
    public void setPrimerNombreEmpleado(String primerNombreEmpleado) {
        this.primerNombreEmpleado = primerNombreEmpleado;
    }
    public String getSegundoNombreEmpleado() {
        return this.segundoNombreEmpleado;
    }
    
    public void setSegundoNombreEmpleado(String segundoNombreEmpleado) {
        this.segundoNombreEmpleado = segundoNombreEmpleado;
    }
    public String getPrimerApellidoEmpleado() {
        return this.primerApellidoEmpleado;
    }
    
    public void setPrimerApellidoEmpleado(String primerApellidoEmpleado) {
        this.primerApellidoEmpleado = primerApellidoEmpleado;
    }
    public String getSegundoApellidoEmpleado() {
        return this.segundoApellidoEmpleado;
    }
    
    public void setSegundoApellidoEmpleado(String segundoApellidoEmpleado) {
        this.segundoApellidoEmpleado = segundoApellidoEmpleado;
    }
    public Date getFechaContratacion() {
        return this.fechaContratacion;
    }
    
    public void setFechaContratacion(Date fechaContratacion) {
        this.fechaContratacion = fechaContratacion;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getTelefonoEmpleado() {
        return this.telefonoEmpleado;
    }
    
    public void setTelefonoEmpleado(String telefonoEmpleado) {
        this.telefonoEmpleado = telefonoEmpleado;
    }
    public String getCedulaEmpleado() {
        return this.cedulaEmpleado;
    }
    
    public void setCedulaEmpleado(String cedulaEmpleado) {
        this.cedulaEmpleado = cedulaEmpleado;
    }
    public String getCorreoEmpleado() {
        return this.correoEmpleado;
    }
    
    public void setCorreoEmpleado(String correoEmpleado) {
        this.correoEmpleado = correoEmpleado;
    }
    public String getDireccionEmpleado() {
        return this.direccionEmpleado;
    }
    
    public void setDireccionEmpleado(String direccionEmpleado) {
        this.direccionEmpleado = direccionEmpleado;
    }
    public byte[] getFotografiaEmpleado() {
        return this.fotografiaEmpleado;
    }
    
    public void setFotografiaEmpleado(byte[] fotografiaEmpleado) {
        this.fotografiaEmpleado = fotografiaEmpleado;
    }
    public String getSexoEmpleado() {
        return this.sexoEmpleado;
    }
    
    public void setSexoEmpleado(String sexoEmpleado) {
        this.sexoEmpleado = sexoEmpleado;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }
    public Set getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set prestamos) {
        this.prestamos = prestamos;
    }
    public Set getInventarioGenerals() {
        return this.inventarioGenerals;
    }
    
    public void setInventarioGenerals(Set inventarioGenerals) {
        this.inventarioGenerals = inventarioGenerals;
    }
    public Set getDevolucionCompras() {
        return this.devolucionCompras;
    }
    
    public void setDevolucionCompras(Set devolucionCompras) {
        this.devolucionCompras = devolucionCompras;
    }
    public Set getHrsExtrases() {
        return this.hrsExtrases;
    }
    
    public void setHrsExtrases(Set hrsExtrases) {
        this.hrsExtrases = hrsExtrases;
    }
    public Set getNominas() {
        return this.nominas;
    }
    
    public void setNominas(Set nominas) {
        this.nominas = nominas;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


