package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1



/**
 * Especialidad generated by hbm2java
 */
public class Especialidad  implements java.io.Serializable {


     private Integer idEspecialidad;
     private Medico medico;
     private String nombreEspecialidad;

    public Especialidad() {
    }

    public Especialidad(Medico medico, String nombreEspecialidad) {
       this.medico = medico;
       this.nombreEspecialidad = nombreEspecialidad;
    }
   
    public Integer getIdEspecialidad() {
        return this.idEspecialidad;
    }
    
    public void setIdEspecialidad(Integer idEspecialidad) {
        this.idEspecialidad = idEspecialidad;
    }
    public Medico getMedico() {
        return this.medico;
    }
    
    public void setMedico(Medico medico) {
        this.medico = medico;
    }
    public String getNombreEspecialidad() {
        return this.nombreEspecialidad;
    }
    
    public void setNombreEspecialidad(String nombreEspecialidad) {
        this.nombreEspecialidad = nombreEspecialidad;
    }




}


