package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ExpedientePaciente generated by hbm2java
 */
public class ExpedientePaciente  implements java.io.Serializable {


     private Integer idHistorialPaciente;
     private Cita cita;
     private Enfermedades enfermedades;
     private Paciente paciente;
     private PacienteInterno pacienteInterno;
     private Integer idExamenesRealizados;
     private Integer idConsultasRealizadas;
     private Date fechaRegistro;

    public ExpedientePaciente() {
    }

	
    public ExpedientePaciente(Paciente paciente, Date fechaRegistro) {
        this.paciente = paciente;
        this.fechaRegistro = fechaRegistro;
    }
    public ExpedientePaciente(Cita cita, Enfermedades enfermedades, Paciente paciente, PacienteInterno pacienteInterno, Integer idExamenesRealizados, Integer idConsultasRealizadas, Date fechaRegistro) {
       this.cita = cita;
       this.enfermedades = enfermedades;
       this.paciente = paciente;
       this.pacienteInterno = pacienteInterno;
       this.idExamenesRealizados = idExamenesRealizados;
       this.idConsultasRealizadas = idConsultasRealizadas;
       this.fechaRegistro = fechaRegistro;
    }
   
    public Integer getIdHistorialPaciente() {
        return this.idHistorialPaciente;
    }
    
    public void setIdHistorialPaciente(Integer idHistorialPaciente) {
        this.idHistorialPaciente = idHistorialPaciente;
    }
    public Cita getCita() {
        return this.cita;
    }
    
    public void setCita(Cita cita) {
        this.cita = cita;
    }
    public Enfermedades getEnfermedades() {
        return this.enfermedades;
    }
    
    public void setEnfermedades(Enfermedades enfermedades) {
        this.enfermedades = enfermedades;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public PacienteInterno getPacienteInterno() {
        return this.pacienteInterno;
    }
    
    public void setPacienteInterno(PacienteInterno pacienteInterno) {
        this.pacienteInterno = pacienteInterno;
    }
    public Integer getIdExamenesRealizados() {
        return this.idExamenesRealizados;
    }
    
    public void setIdExamenesRealizados(Integer idExamenesRealizados) {
        this.idExamenesRealizados = idExamenesRealizados;
    }
    public Integer getIdConsultasRealizadas() {
        return this.idConsultasRealizadas;
    }
    
    public void setIdConsultasRealizadas(Integer idConsultasRealizadas) {
        this.idConsultasRealizadas = idConsultasRealizadas;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


