package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * InventarioGeneral generated by hbm2java
 */
public class InventarioGeneral  implements java.io.Serializable {


     private Integer idInventarioGeneral;
     private DetalleCompra detalleCompra;
     private EmpleadoLaboratorio empleadoLaboratorio;
     private Producto producto;
     private Date fechaInventario;
     private int unidadesInactivas;
     private BigDecimal costoUnit;

    public InventarioGeneral() {
    }

    public InventarioGeneral(DetalleCompra detalleCompra, EmpleadoLaboratorio empleadoLaboratorio, Producto producto, Date fechaInventario, int unidadesInactivas, BigDecimal costoUnit) {
       this.detalleCompra = detalleCompra;
       this.empleadoLaboratorio = empleadoLaboratorio;
       this.producto = producto;
       this.fechaInventario = fechaInventario;
       this.unidadesInactivas = unidadesInactivas;
       this.costoUnit = costoUnit;
    }
   
    public Integer getIdInventarioGeneral() {
        return this.idInventarioGeneral;
    }
    
    public void setIdInventarioGeneral(Integer idInventarioGeneral) {
        this.idInventarioGeneral = idInventarioGeneral;
    }
    public DetalleCompra getDetalleCompra() {
        return this.detalleCompra;
    }
    
    public void setDetalleCompra(DetalleCompra detalleCompra) {
        this.detalleCompra = detalleCompra;
    }
    public EmpleadoLaboratorio getEmpleadoLaboratorio() {
        return this.empleadoLaboratorio;
    }
    
    public void setEmpleadoLaboratorio(EmpleadoLaboratorio empleadoLaboratorio) {
        this.empleadoLaboratorio = empleadoLaboratorio;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Date getFechaInventario() {
        return this.fechaInventario;
    }
    
    public void setFechaInventario(Date fechaInventario) {
        this.fechaInventario = fechaInventario;
    }
    public int getUnidadesInactivas() {
        return this.unidadesInactivas;
    }
    
    public void setUnidadesInactivas(int unidadesInactivas) {
        this.unidadesInactivas = unidadesInactivas;
    }
    public BigDecimal getCostoUnit() {
        return this.costoUnit;
    }
    
    public void setCostoUnit(BigDecimal costoUnit) {
        this.costoUnit = costoUnit;
    }




}


