package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Laboratorio generated by hbm2java
 */
public class Laboratorio  implements java.io.Serializable {


     private Integer idLaboratorio;
     private String nombreLaboratorio;
     private String direccionLaboratorio;
     private String telefonoLaboratorio;
     private String correoLaboratorio;
     private boolean estadoLaboratorio;
     private Set empleadoLaboratorios = new HashSet(0);

    public Laboratorio() {
    }

	
    public Laboratorio(String nombreLaboratorio, String direccionLaboratorio, String telefonoLaboratorio, String correoLaboratorio, boolean estadoLaboratorio) {
        this.nombreLaboratorio = nombreLaboratorio;
        this.direccionLaboratorio = direccionLaboratorio;
        this.telefonoLaboratorio = telefonoLaboratorio;
        this.correoLaboratorio = correoLaboratorio;
        this.estadoLaboratorio = estadoLaboratorio;
    }
    public Laboratorio(String nombreLaboratorio, String direccionLaboratorio, String telefonoLaboratorio, String correoLaboratorio, boolean estadoLaboratorio, Set empleadoLaboratorios) {
       this.nombreLaboratorio = nombreLaboratorio;
       this.direccionLaboratorio = direccionLaboratorio;
       this.telefonoLaboratorio = telefonoLaboratorio;
       this.correoLaboratorio = correoLaboratorio;
       this.estadoLaboratorio = estadoLaboratorio;
       this.empleadoLaboratorios = empleadoLaboratorios;
    }
   
    public Integer getIdLaboratorio() {
        return this.idLaboratorio;
    }
    
    public void setIdLaboratorio(Integer idLaboratorio) {
        this.idLaboratorio = idLaboratorio;
    }
    public String getNombreLaboratorio() {
        return this.nombreLaboratorio;
    }
    
    public void setNombreLaboratorio(String nombreLaboratorio) {
        this.nombreLaboratorio = nombreLaboratorio;
    }
    public String getDireccionLaboratorio() {
        return this.direccionLaboratorio;
    }
    
    public void setDireccionLaboratorio(String direccionLaboratorio) {
        this.direccionLaboratorio = direccionLaboratorio;
    }
    public String getTelefonoLaboratorio() {
        return this.telefonoLaboratorio;
    }
    
    public void setTelefonoLaboratorio(String telefonoLaboratorio) {
        this.telefonoLaboratorio = telefonoLaboratorio;
    }
    public String getCorreoLaboratorio() {
        return this.correoLaboratorio;
    }
    
    public void setCorreoLaboratorio(String correoLaboratorio) {
        this.correoLaboratorio = correoLaboratorio;
    }
    public boolean isEstadoLaboratorio() {
        return this.estadoLaboratorio;
    }
    
    public void setEstadoLaboratorio(boolean estadoLaboratorio) {
        this.estadoLaboratorio = estadoLaboratorio;
    }
    public Set getEmpleadoLaboratorios() {
        return this.empleadoLaboratorios;
    }
    
    public void setEmpleadoLaboratorios(Set empleadoLaboratorios) {
        this.empleadoLaboratorios = empleadoLaboratorios;
    }




}


