package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Nomina generated by hbm2java
 */
public class Nomina  implements java.io.Serializable {


     private Integer idNomina;
     private Cajero cajero;
     private EmpleadoLaboratorio empleadoLaboratorio;
     private Medico medico;
     private int noNomina;
     private Date fechaNomina;
     private BigDecimal salarioBasico;
     private int cantidadHrsExtras;
     private BigDecimal pagoHrsExtras;
     private int aniosAntiguedad;
     private BigDecimal antiguedad;
     private BigDecimal totalIngresos;
     private BigDecimal inssL;
     private BigDecimal ir;
     private BigDecimal totalDeducciones;
     private BigDecimal salarioNeto;
     private BigDecimal otrasDeducciones;
     private BigDecimal salarioPagar;
     private BigDecimal inssP;
     private BigDecimal inatec;
     private BigDecimal vacaciones;
     private BigDecimal treceavoMes;
     private String estadoNomina;

    public Nomina() {
    }

    public Nomina(Cajero cajero, EmpleadoLaboratorio empleadoLaboratorio, Medico medico, int noNomina, Date fechaNomina, BigDecimal salarioBasico, int cantidadHrsExtras, BigDecimal pagoHrsExtras, int aniosAntiguedad, BigDecimal antiguedad, BigDecimal totalIngresos, BigDecimal inssL, BigDecimal ir, BigDecimal totalDeducciones, BigDecimal salarioNeto, BigDecimal otrasDeducciones, BigDecimal salarioPagar, BigDecimal inssP, BigDecimal inatec, BigDecimal vacaciones, BigDecimal treceavoMes, String estadoNomina) {
       this.cajero = cajero;
       this.empleadoLaboratorio = empleadoLaboratorio;
       this.medico = medico;
       this.noNomina = noNomina;
       this.fechaNomina = fechaNomina;
       this.salarioBasico = salarioBasico;
       this.cantidadHrsExtras = cantidadHrsExtras;
       this.pagoHrsExtras = pagoHrsExtras;
       this.aniosAntiguedad = aniosAntiguedad;
       this.antiguedad = antiguedad;
       this.totalIngresos = totalIngresos;
       this.inssL = inssL;
       this.ir = ir;
       this.totalDeducciones = totalDeducciones;
       this.salarioNeto = salarioNeto;
       this.otrasDeducciones = otrasDeducciones;
       this.salarioPagar = salarioPagar;
       this.inssP = inssP;
       this.inatec = inatec;
       this.vacaciones = vacaciones;
       this.treceavoMes = treceavoMes;
       this.estadoNomina = estadoNomina;
    }
   
    public Integer getIdNomina() {
        return this.idNomina;
    }
    
    public void setIdNomina(Integer idNomina) {
        this.idNomina = idNomina;
    }
    public Cajero getCajero() {
        return this.cajero;
    }
    
    public void setCajero(Cajero cajero) {
        this.cajero = cajero;
    }
    public EmpleadoLaboratorio getEmpleadoLaboratorio() {
        return this.empleadoLaboratorio;
    }
    
    public void setEmpleadoLaboratorio(EmpleadoLaboratorio empleadoLaboratorio) {
        this.empleadoLaboratorio = empleadoLaboratorio;
    }
    public Medico getMedico() {
        return this.medico;
    }
    
    public void setMedico(Medico medico) {
        this.medico = medico;
    }
    public int getNoNomina() {
        return this.noNomina;
    }
    
    public void setNoNomina(int noNomina) {
        this.noNomina = noNomina;
    }
    public Date getFechaNomina() {
        return this.fechaNomina;
    }
    
    public void setFechaNomina(Date fechaNomina) {
        this.fechaNomina = fechaNomina;
    }
    public BigDecimal getSalarioBasico() {
        return this.salarioBasico;
    }
    
    public void setSalarioBasico(BigDecimal salarioBasico) {
        this.salarioBasico = salarioBasico;
    }
    public int getCantidadHrsExtras() {
        return this.cantidadHrsExtras;
    }
    
    public void setCantidadHrsExtras(int cantidadHrsExtras) {
        this.cantidadHrsExtras = cantidadHrsExtras;
    }
    public BigDecimal getPagoHrsExtras() {
        return this.pagoHrsExtras;
    }
    
    public void setPagoHrsExtras(BigDecimal pagoHrsExtras) {
        this.pagoHrsExtras = pagoHrsExtras;
    }
    public int getAniosAntiguedad() {
        return this.aniosAntiguedad;
    }
    
    public void setAniosAntiguedad(int aniosAntiguedad) {
        this.aniosAntiguedad = aniosAntiguedad;
    }
    public BigDecimal getAntiguedad() {
        return this.antiguedad;
    }
    
    public void setAntiguedad(BigDecimal antiguedad) {
        this.antiguedad = antiguedad;
    }
    public BigDecimal getTotalIngresos() {
        return this.totalIngresos;
    }
    
    public void setTotalIngresos(BigDecimal totalIngresos) {
        this.totalIngresos = totalIngresos;
    }
    public BigDecimal getInssL() {
        return this.inssL;
    }
    
    public void setInssL(BigDecimal inssL) {
        this.inssL = inssL;
    }
    public BigDecimal getIr() {
        return this.ir;
    }
    
    public void setIr(BigDecimal ir) {
        this.ir = ir;
    }
    public BigDecimal getTotalDeducciones() {
        return this.totalDeducciones;
    }
    
    public void setTotalDeducciones(BigDecimal totalDeducciones) {
        this.totalDeducciones = totalDeducciones;
    }
    public BigDecimal getSalarioNeto() {
        return this.salarioNeto;
    }
    
    public void setSalarioNeto(BigDecimal salarioNeto) {
        this.salarioNeto = salarioNeto;
    }
    public BigDecimal getOtrasDeducciones() {
        return this.otrasDeducciones;
    }
    
    public void setOtrasDeducciones(BigDecimal otrasDeducciones) {
        this.otrasDeducciones = otrasDeducciones;
    }
    public BigDecimal getSalarioPagar() {
        return this.salarioPagar;
    }
    
    public void setSalarioPagar(BigDecimal salarioPagar) {
        this.salarioPagar = salarioPagar;
    }
    public BigDecimal getInssP() {
        return this.inssP;
    }
    
    public void setInssP(BigDecimal inssP) {
        this.inssP = inssP;
    }
    public BigDecimal getInatec() {
        return this.inatec;
    }
    
    public void setInatec(BigDecimal inatec) {
        this.inatec = inatec;
    }
    public BigDecimal getVacaciones() {
        return this.vacaciones;
    }
    
    public void setVacaciones(BigDecimal vacaciones) {
        this.vacaciones = vacaciones;
    }
    public BigDecimal getTreceavoMes() {
        return this.treceavoMes;
    }
    
    public void setTreceavoMes(BigDecimal treceavoMes) {
        this.treceavoMes = treceavoMes;
    }
    public String getEstadoNomina() {
        return this.estadoNomina;
    }
    
    public void setEstadoNomina(String estadoNomina) {
        this.estadoNomina = estadoNomina;
    }




}


