package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PacienteInterno generated by hbm2java
 */
public class PacienteInterno  implements java.io.Serializable {


     private Integer idPaciente;
     private Enfermera enfermera;
     private Pais pais;
     private Date fechaIngreso;
     private Date fechaSalida;
     private String cedula;
     private String primerNombre;
     private String segundoNombre;
     private String primerApellido;
     private String segundoApellido;
     private String convencional;
     private String celular;
     private int edad;
     private String direccion;
     private Boolean menorEdad;
     private boolean estado;
     private Set expedientePacientes = new HashSet(0);

    public PacienteInterno() {
    }

	
    public PacienteInterno(Enfermera enfermera, Pais pais, Date fechaIngreso, Date fechaSalida, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, String convencional, String celular, int edad, String direccion, boolean estado) {
        this.enfermera = enfermera;
        this.pais = pais;
        this.fechaIngreso = fechaIngreso;
        this.fechaSalida = fechaSalida;
        this.primerNombre = primerNombre;
        this.segundoNombre = segundoNombre;
        this.primerApellido = primerApellido;
        this.segundoApellido = segundoApellido;
        this.convencional = convencional;
        this.celular = celular;
        this.edad = edad;
        this.direccion = direccion;
        this.estado = estado;
    }
    public PacienteInterno(Enfermera enfermera, Pais pais, Date fechaIngreso, Date fechaSalida, String cedula, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, String convencional, String celular, int edad, String direccion, Boolean menorEdad, boolean estado, Set expedientePacientes) {
       this.enfermera = enfermera;
       this.pais = pais;
       this.fechaIngreso = fechaIngreso;
       this.fechaSalida = fechaSalida;
       this.cedula = cedula;
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.convencional = convencional;
       this.celular = celular;
       this.edad = edad;
       this.direccion = direccion;
       this.menorEdad = menorEdad;
       this.estado = estado;
       this.expedientePacientes = expedientePacientes;
    }
   
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }
    public Enfermera getEnfermera() {
        return this.enfermera;
    }
    
    public void setEnfermera(Enfermera enfermera) {
        this.enfermera = enfermera;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public String getConvencional() {
        return this.convencional;
    }
    
    public void setConvencional(String convencional) {
        this.convencional = convencional;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Boolean getMenorEdad() {
        return this.menorEdad;
    }
    
    public void setMenorEdad(Boolean menorEdad) {
        this.menorEdad = menorEdad;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getExpedientePacientes() {
        return this.expedientePacientes;
    }
    
    public void setExpedientePacientes(Set expedientePacientes) {
        this.expedientePacientes = expedientePacientes;
    }




}


