package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private Integer idPais;
     private Boolean extranjero;
     private String paisNacimiento;
     private Set pacienteInternos = new HashSet(0);
     private Set departamentos = new HashSet(0);
     private Set pacientes = new HashSet(0);

    public Pais() {
    }

    public Pais(Boolean extranjero, String paisNacimiento, Set pacienteInternos, Set departamentos, Set pacientes) {
       this.extranjero = extranjero;
       this.paisNacimiento = paisNacimiento;
       this.pacienteInternos = pacienteInternos;
       this.departamentos = departamentos;
       this.pacientes = pacientes;
    }
   
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }
    public Boolean getExtranjero() {
        return this.extranjero;
    }
    
    public void setExtranjero(Boolean extranjero) {
        this.extranjero = extranjero;
    }
    public String getPaisNacimiento() {
        return this.paisNacimiento;
    }
    
    public void setPaisNacimiento(String paisNacimiento) {
        this.paisNacimiento = paisNacimiento;
    }
    public Set getPacienteInternos() {
        return this.pacienteInternos;
    }
    
    public void setPacienteInternos(Set pacienteInternos) {
        this.pacienteInternos = pacienteInternos;
    }
    public Set getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set departamentos) {
        this.departamentos = departamentos;
    }
    public Set getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set pacientes) {
        this.pacientes = pacientes;
    }




}


