package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private Integer idPrestamo;
     private Cajero cajero;
     private EmpleadoLaboratorio empleadoLaboratorio;
     private Medico medico;
     private BigDecimal prestamo;
     private Date fecha;
     private String estadoPrestamo;

    public Prestamo() {
    }

    public Prestamo(Cajero cajero, EmpleadoLaboratorio empleadoLaboratorio, Medico medico, BigDecimal prestamo, Date fecha, String estadoPrestamo) {
       this.cajero = cajero;
       this.empleadoLaboratorio = empleadoLaboratorio;
       this.medico = medico;
       this.prestamo = prestamo;
       this.fecha = fecha;
       this.estadoPrestamo = estadoPrestamo;
    }
   
    public Integer getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(Integer idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public Cajero getCajero() {
        return this.cajero;
    }
    
    public void setCajero(Cajero cajero) {
        this.cajero = cajero;
    }
    public EmpleadoLaboratorio getEmpleadoLaboratorio() {
        return this.empleadoLaboratorio;
    }
    
    public void setEmpleadoLaboratorio(EmpleadoLaboratorio empleadoLaboratorio) {
        this.empleadoLaboratorio = empleadoLaboratorio;
    }
    public Medico getMedico() {
        return this.medico;
    }
    
    public void setMedico(Medico medico) {
        this.medico = medico;
    }
    public BigDecimal getPrestamo() {
        return this.prestamo;
    }
    
    public void setPrestamo(BigDecimal prestamo) {
        this.prestamo = prestamo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getEstadoPrestamo() {
        return this.estadoPrestamo;
    }
    
    public void setEstadoPrestamo(String estadoPrestamo) {
        this.estadoPrestamo = estadoPrestamo;
    }




}


