package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private Proveedor proveedor;
     private String nombreProducto;
     private String codigoProducto;
     private String categoria;
     private String descripcion;
     private String controlado;
     private int unidadesDisponibles;
     private BigDecimal precioVentaUnit;
     private int stockMin;
     private byte[] imagenProducto;
     private float margenGanancia;
     private boolean estadoProducto;
     private String desactivadoDirectamente;
     private Set detalleCompras = new HashSet(0);
     private Set inventarioGenerals = new HashSet(0);
     private Set detalleVentas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(Proveedor proveedor, String nombreProducto, String codigoProducto, String categoria, String descripcion, String controlado, int unidadesDisponibles, BigDecimal precioVentaUnit, int stockMin, float margenGanancia, boolean estadoProducto, String desactivadoDirectamente) {
        this.proveedor = proveedor;
        this.nombreProducto = nombreProducto;
        this.codigoProducto = codigoProducto;
        this.categoria = categoria;
        this.descripcion = descripcion;
        this.controlado = controlado;
        this.unidadesDisponibles = unidadesDisponibles;
        this.precioVentaUnit = precioVentaUnit;
        this.stockMin = stockMin;
        this.margenGanancia = margenGanancia;
        this.estadoProducto = estadoProducto;
        this.desactivadoDirectamente = desactivadoDirectamente;
    }
    public Producto(Proveedor proveedor, String nombreProducto, String codigoProducto, String categoria, String descripcion, String controlado, int unidadesDisponibles, BigDecimal precioVentaUnit, int stockMin, byte[] imagenProducto, float margenGanancia, boolean estadoProducto, String desactivadoDirectamente, Set detalleCompras, Set inventarioGenerals, Set detalleVentas) {
       this.proveedor = proveedor;
       this.nombreProducto = nombreProducto;
       this.codigoProducto = codigoProducto;
       this.categoria = categoria;
       this.descripcion = descripcion;
       this.controlado = controlado;
       this.unidadesDisponibles = unidadesDisponibles;
       this.precioVentaUnit = precioVentaUnit;
       this.stockMin = stockMin;
       this.imagenProducto = imagenProducto;
       this.margenGanancia = margenGanancia;
       this.estadoProducto = estadoProducto;
       this.desactivadoDirectamente = desactivadoDirectamente;
       this.detalleCompras = detalleCompras;
       this.inventarioGenerals = inventarioGenerals;
       this.detalleVentas = detalleVentas;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public String getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(String codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getControlado() {
        return this.controlado;
    }
    
    public void setControlado(String controlado) {
        this.controlado = controlado;
    }
    public int getUnidadesDisponibles() {
        return this.unidadesDisponibles;
    }
    
    public void setUnidadesDisponibles(int unidadesDisponibles) {
        this.unidadesDisponibles = unidadesDisponibles;
    }
    public BigDecimal getPrecioVentaUnit() {
        return this.precioVentaUnit;
    }
    
    public void setPrecioVentaUnit(BigDecimal precioVentaUnit) {
        this.precioVentaUnit = precioVentaUnit;
    }
    public int getStockMin() {
        return this.stockMin;
    }
    
    public void setStockMin(int stockMin) {
        this.stockMin = stockMin;
    }
    public byte[] getImagenProducto() {
        return this.imagenProducto;
    }
    
    public void setImagenProducto(byte[] imagenProducto) {
        this.imagenProducto = imagenProducto;
    }
    public float getMargenGanancia() {
        return this.margenGanancia;
    }
    
    public void setMargenGanancia(float margenGanancia) {
        this.margenGanancia = margenGanancia;
    }
    public boolean isEstadoProducto() {
        return this.estadoProducto;
    }
    
    public void setEstadoProducto(boolean estadoProducto) {
        this.estadoProducto = estadoProducto;
    }
    public String getDesactivadoDirectamente() {
        return this.desactivadoDirectamente;
    }
    
    public void setDesactivadoDirectamente(String desactivadoDirectamente) {
        this.desactivadoDirectamente = desactivadoDirectamente;
    }
    public Set getDetalleCompras() {
        return this.detalleCompras;
    }
    
    public void setDetalleCompras(Set detalleCompras) {
        this.detalleCompras = detalleCompras;
    }
    public Set getInventarioGenerals() {
        return this.inventarioGenerals;
    }
    
    public void setInventarioGenerals(Set inventarioGenerals) {
        this.inventarioGenerals = inventarioGenerals;
    }
    public Set getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set detalleVentas) {
        this.detalleVentas = detalleVentas;
    }




}


