package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private String tipoProveedor;
     private String nombreProveedor;
     private String noRuc;
     private String telefonoProveedor;
     private String direccionProveedor;
     private String correoProveedor;
     private boolean estadoProveedor;
     private Set compras = new HashSet(0);
     private Set productos = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(String tipoProveedor, String nombreProveedor, String noRuc, String telefonoProveedor, String direccionProveedor, String correoProveedor, boolean estadoProveedor) {
        this.tipoProveedor = tipoProveedor;
        this.nombreProveedor = nombreProveedor;
        this.noRuc = noRuc;
        this.telefonoProveedor = telefonoProveedor;
        this.direccionProveedor = direccionProveedor;
        this.correoProveedor = correoProveedor;
        this.estadoProveedor = estadoProveedor;
    }
    public Proveedor(String tipoProveedor, String nombreProveedor, String noRuc, String telefonoProveedor, String direccionProveedor, String correoProveedor, boolean estadoProveedor, Set compras, Set productos) {
       this.tipoProveedor = tipoProveedor;
       this.nombreProveedor = nombreProveedor;
       this.noRuc = noRuc;
       this.telefonoProveedor = telefonoProveedor;
       this.direccionProveedor = direccionProveedor;
       this.correoProveedor = correoProveedor;
       this.estadoProveedor = estadoProveedor;
       this.compras = compras;
       this.productos = productos;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getTipoProveedor() {
        return this.tipoProveedor;
    }
    
    public void setTipoProveedor(String tipoProveedor) {
        this.tipoProveedor = tipoProveedor;
    }
    public String getNombreProveedor() {
        return this.nombreProveedor;
    }
    
    public void setNombreProveedor(String nombreProveedor) {
        this.nombreProveedor = nombreProveedor;
    }
    public String getNoRuc() {
        return this.noRuc;
    }
    
    public void setNoRuc(String noRuc) {
        this.noRuc = noRuc;
    }
    public String getTelefonoProveedor() {
        return this.telefonoProveedor;
    }
    
    public void setTelefonoProveedor(String telefonoProveedor) {
        this.telefonoProveedor = telefonoProveedor;
    }
    public String getDireccionProveedor() {
        return this.direccionProveedor;
    }
    
    public void setDireccionProveedor(String direccionProveedor) {
        this.direccionProveedor = direccionProveedor;
    }
    public String getCorreoProveedor() {
        return this.correoProveedor;
    }
    
    public void setCorreoProveedor(String correoProveedor) {
        this.correoProveedor = correoProveedor;
    }
    public boolean isEstadoProveedor() {
        return this.estadoProveedor;
    }
    
    public void setEstadoProveedor(boolean estadoProveedor) {
        this.estadoProveedor = estadoProveedor;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


