package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoCambio generated by hbm2java
 */
public class TipoCambio  implements java.io.Serializable {


     private Integer idTipoCambio;
     private BigDecimal tipoCambio;
     private Date fecha;
     private boolean estadoTipoCambio;
     private Set compras = new HashSet(0);
     private Set ventas = new HashSet(0);

    public TipoCambio() {
    }

	
    public TipoCambio(BigDecimal tipoCambio, Date fecha, boolean estadoTipoCambio) {
        this.tipoCambio = tipoCambio;
        this.fecha = fecha;
        this.estadoTipoCambio = estadoTipoCambio;
    }
    public TipoCambio(BigDecimal tipoCambio, Date fecha, boolean estadoTipoCambio, Set compras, Set ventas) {
       this.tipoCambio = tipoCambio;
       this.fecha = fecha;
       this.estadoTipoCambio = estadoTipoCambio;
       this.compras = compras;
       this.ventas = ventas;
    }
   
    public Integer getIdTipoCambio() {
        return this.idTipoCambio;
    }
    
    public void setIdTipoCambio(Integer idTipoCambio) {
        this.idTipoCambio = idTipoCambio;
    }
    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public boolean isEstadoTipoCambio() {
        return this.estadoTipoCambio;
    }
    
    public void setEstadoTipoCambio(boolean estadoTipoCambio) {
        this.estadoTipoCambio = estadoTipoCambio;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


