package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String privilegio;
     private String nombreUsuario;
     private String correoUsuario;
     private String contrasena;
     private boolean estadoUsuario;
     private Set enfermeras = new HashSet(0);
     private Set pacientes = new HashSet(0);
     private Set empleadoLaboratorios = new HashSet(0);
     private Set medicos = new HashSet(0);
     private Set cajeros = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String privilegio, String nombreUsuario, String contrasena, boolean estadoUsuario) {
        this.privilegio = privilegio;
        this.nombreUsuario = nombreUsuario;
        this.contrasena = contrasena;
        this.estadoUsuario = estadoUsuario;
    }
    public Usuario(String privilegio, String nombreUsuario, String correoUsuario, String contrasena, boolean estadoUsuario, Set enfermeras, Set pacientes, Set empleadoLaboratorios, Set medicos, Set cajeros) {
       this.privilegio = privilegio;
       this.nombreUsuario = nombreUsuario;
       this.correoUsuario = correoUsuario;
       this.contrasena = contrasena;
       this.estadoUsuario = estadoUsuario;
       this.enfermeras = enfermeras;
       this.pacientes = pacientes;
       this.empleadoLaboratorios = empleadoLaboratorios;
       this.medicos = medicos;
       this.cajeros = cajeros;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getPrivilegio() {
        return this.privilegio;
    }
    
    public void setPrivilegio(String privilegio) {
        this.privilegio = privilegio;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getCorreoUsuario() {
        return this.correoUsuario;
    }
    
    public void setCorreoUsuario(String correoUsuario) {
        this.correoUsuario = correoUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public boolean isEstadoUsuario() {
        return this.estadoUsuario;
    }
    
    public void setEstadoUsuario(boolean estadoUsuario) {
        this.estadoUsuario = estadoUsuario;
    }
    public Set getEnfermeras() {
        return this.enfermeras;
    }
    
    public void setEnfermeras(Set enfermeras) {
        this.enfermeras = enfermeras;
    }
    public Set getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set pacientes) {
        this.pacientes = pacientes;
    }
    public Set getEmpleadoLaboratorios() {
        return this.empleadoLaboratorios;
    }
    
    public void setEmpleadoLaboratorios(Set empleadoLaboratorios) {
        this.empleadoLaboratorios = empleadoLaboratorios;
    }
    public Set getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Set medicos) {
        this.medicos = medicos;
    }
    public Set getCajeros() {
        return this.cajeros;
    }
    
    public void setCajeros(Set cajeros) {
        this.cajeros = cajeros;
    }




}


