package Pojos;
// Generated Sep 19, 2015 12:30:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer idVenta;
     private EmpleadoLaboratorio empleadoLaboratorio;
     private TipoCambio tipoCambio;
     private String cliente;
     private Date fechaVenta;
     private BigDecimal subTotalVendido;
     private float descuento;
     private String tipoMoneda;
     private String modoVenta;
     private Set detalleVentas = new HashSet(0);

    public Venta() {
    }

	
    public Venta(EmpleadoLaboratorio empleadoLaboratorio, TipoCambio tipoCambio, String cliente, Date fechaVenta, BigDecimal subTotalVendido, float descuento, String tipoMoneda, String modoVenta) {
        this.empleadoLaboratorio = empleadoLaboratorio;
        this.tipoCambio = tipoCambio;
        this.cliente = cliente;
        this.fechaVenta = fechaVenta;
        this.subTotalVendido = subTotalVendido;
        this.descuento = descuento;
        this.tipoMoneda = tipoMoneda;
        this.modoVenta = modoVenta;
    }
    public Venta(EmpleadoLaboratorio empleadoLaboratorio, TipoCambio tipoCambio, String cliente, Date fechaVenta, BigDecimal subTotalVendido, float descuento, String tipoMoneda, String modoVenta, Set detalleVentas) {
       this.empleadoLaboratorio = empleadoLaboratorio;
       this.tipoCambio = tipoCambio;
       this.cliente = cliente;
       this.fechaVenta = fechaVenta;
       this.subTotalVendido = subTotalVendido;
       this.descuento = descuento;
       this.tipoMoneda = tipoMoneda;
       this.modoVenta = modoVenta;
       this.detalleVentas = detalleVentas;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public EmpleadoLaboratorio getEmpleadoLaboratorio() {
        return this.empleadoLaboratorio;
    }
    
    public void setEmpleadoLaboratorio(EmpleadoLaboratorio empleadoLaboratorio) {
        this.empleadoLaboratorio = empleadoLaboratorio;
    }
    public TipoCambio getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(TipoCambio tipoCambio) {
        this.tipoCambio = tipoCambio;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public BigDecimal getSubTotalVendido() {
        return this.subTotalVendido;
    }
    
    public void setSubTotalVendido(BigDecimal subTotalVendido) {
        this.subTotalVendido = subTotalVendido;
    }
    public float getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(float descuento) {
        this.descuento = descuento;
    }
    public String getTipoMoneda() {
        return this.tipoMoneda;
    }
    
    public void setTipoMoneda(String tipoMoneda) {
        this.tipoMoneda = tipoMoneda;
    }
    public String getModoVenta() {
        return this.modoVenta;
    }
    
    public void setModoVenta(String modoVenta) {
        this.modoVenta = modoVenta;
    }
    public Set getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set detalleVentas) {
        this.detalleVentas = detalleVentas;
    }




}


